### ISSUE TITLE
README: BOM -> BOMB

### ISSUE THREAD

**Issue by JamesLee92** [takecore/csv-encode-is-absolutely-utf16#1]
スペルミスです。

**Comment by takecore** [comment]
@JamesLee92 
`BOM` means `byte order mark`.
[See Wikipedia](https://ja.wikipedia.org/wiki/%E3%83%90%E3%82%A4%E3%83%88%E3%82%AA%E3%83%BC%E3%83%80%E3%83%BC%E3%83%9E%E3%83%BC%E3%82%AF)

**Comment by JamesLee92** [comment]
なるほど、有り難うございます！
